name: Tests on Linux with static build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install python-setuptools libboost-dev libz3-dev
      - name: Install Capstone
        run: |
          wget https://github.com/aquynh/capstone/archive/4.0.2.tar.gz
          tar -xf ./4.0.2.tar.gz
          cd ./capstone-4.0.2
          bash ./make.sh
          sudo make install
          cd ../
      - name: Compile Triton
        run: |
          mkdir ./build
          cd ./build
          cmake -DBUILD_SHARED_LIBS=off ..
          sudo make -j3 install
      - name: Unittests
        run: |
          make -C build check
